# FROM redis
FROM redis:alpine

ARG REDIS_PASSWORD=redis

COPY ./docker/redis/redis.conf /usr/local/etc/redis/redis.conf

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass ${REDIS_PASSWORD}" ]